#!/usr/bin/env python

from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
from boto.mturk.connection import MTurkConnection
import os


if __name__ == "__main__":
    parser = ArgumentParser(
        formatter_class=ArgumentDefaultsHelpFormatter)

    parser.add_argument(
        "qualification",
        metavar="QUALIFICATION",
        help="Qualification id.")
    parser.add_argument(
        "workers",
        metavar="WORKER",
        nargs="+",
        help="Worker id.")

    args = parser.parse_args()

    print "Connecting to mechanical turk..."
    aws_access_key_id = os.env['AWS_ACCESS_KEY_ID']
    aws_secret_access_key = os.env['AWS_SECRET_ACCESS_KEY']
    conn = MTurkConnection(aws_access_key_id, aws_secret_access_key)

    for worker in args.workers:
       print "Assigning qualification '%s' to worker '%s'" % (args.qualification, worker)
       result = conn.assign_qualification(args.qualification, worker)
       if result != []:
          print result
