#!/bin/sh

if [ $(uname -s) == "Darwin" ]; then
    kinit jhamrick@ATHENA.MIT.EDU
    aklog -force 
else
    killall authloop
    kdestroy
    unlog
    kinit jhamrick@ATHENA.MIT.EDU
    authloop athena csail sipb &
fi
