#!/bin/sh

if [ $(uname -s) == "Darwin" ]; then
    kinit jhamrick@CSAIL.MIT.EDU
    aklog -force
else
    killall authloop
    kdestroy
    unlog
    kinit jhamrick@CSAIL.MIT.EDU
    authloop athena csail &
fi

