#!/bin/bash

SERVERLOC=/tmp/emacs1000

cd $HOME/CS281
\emacs --daemon
mv $SERVERLOC/server $SERVERLOC/cs281

cd $HOME/6.828
\emacs --daemon
mv $SERVERLOC/server $SERVERLOC/6.828

cd $HOME/project/cogphysics/dev/code/cogphysics
\emacs --daemon
mv $SERVERLOC/server $SERVERLOC/cogphysics

cd $HOME
\emacs --daemon